### ISSUE TITLE
Unknown Entity References: `dashboard-sandbox`

### ISSUE THREAD

**Issue by worgarside-hass** [worgarside/home-assistant#1029]
Repair of type `unknown_entity_references` updated for entity `dashboard-sandbox` in domain `lovelace`.

```json
{
  "domain": "spook",
  "event_type": "update",
  "event_types": [
    "create",
    "remove",
    "update"
  ],
  "friendly_name": "Repairs",
  "issue_id": "lovelace_unknown_entity_references_dashboard-sandbox"
}
```

[![Open your Home Assistant instance and show your repairs.](https://my.home-assistant.io/badges/repairs.svg)](https://my.home-assistant.io/redirect/repairs/)

**Comment by worgarside** [comment]
Repair of type `unknown_entity_references` removed for entity `dashboard-sandbox` in domain `lovelace`.

```json
{
  "domain": "spook",
  "event_type": "remove",
  "event_types": [
    "create",
    "remove",
    "update"
  ],
  "friendly_name": "Repairs",
  "issue_id": "lovelace_unknown_entity_references_dashboard-sandbox"
}
```

[![Open your Home Assistant instance and show your repairs.](https://my.home-assistant.io/badges/repairs.svg)](https://my.home-assistant.io/redirect/repairs/)
